# .github/release.yml

changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - bug
        - fix
    - title: Exciting New Features 🎉
      labels:
        - feat
        - enhancement
    - title: Document Update 📚
      label:
        - read me update
        - doc
        - documents
    - title: Newbie start 👶
      label:
        - good first issue
    - title: Duplicate Code 👷
      label:
        - duplicate
        - optimization
        - fix
    - title: Need Help 🆘
      label:
        - help wanted
        - question

